
insert into role(code,name) values('ADMIN','Quản trị');
insert into role(code,name) values('USER','Người dùng');

insert into user(username,password,fullname,status, phone, email)
values('admin','$2a$10$/RUbuT9KIqk6f8enaTQiLOXzhnUkiwEJRdtzdrMXXwU7dgnLKTCYG','Cong Thoai',1, '0983583845', '16521191@gm.uit.edu.vn');
insert into user(username,password,fullname,status, phone, email)
values('user','$2a$10$/RUbuT9KIqk6f8enaTQiLOXzhnUkiwEJRdtzdrMXXwU7dgnLKTCYG','Người dùng 1',1, '0983583845', '16521191@gm.uit.edu.vn');
insert into user(username,password,fullname,status, phone, email)
values('congthoai','$2a$10$/RUbuT9KIqk6f8enaTQiLOXzhnUkiwEJRdtzdrMXXwU7dgnLKTCYG','Công Thoại',1, '0983583845', '16521191@gm.uit.edu.vn');

INSERT INTO user_role(userid,roleid) VALUES (1,1);
INSERT INTO user_role(userid,roleid) VALUES (2,2);
INSERT INTO user_role(userid,roleid) VALUES (3,2);

INSERT into type (name, description, createddate, modifieddate) VALUES ('Đồng hồ cơ', 'Đồng hồ lên dây cót', CURRENT_DATE(),  CURRENT_DATE());
INSERT into type (name, description, createddate, modifieddate) VALUES ('Đồng hồ pin', 'Đồng hồ chạy bằng pin', CURRENT_DATE(),  CURRENT_DATE());
INSERT into type (name, description, createddate, modifieddate) VALUES ('Đồng hồ năng lượng', 'Đồng hồ sạc năng lượng mặt trời', CURRENT_DATE(),  CURRENT_DATE());

INSERT into brand (name, place, description, createddate, modifieddate) VALUES  ('Seiko', 'Japan', 'SX tại nhật', CURRENT_DATE(),  CURRENT_DATE());
INSERT into brand (name, place, description, createddate, modifieddate) VALUES  ('DanielWellington', 'Thụy điển', 'Đồng hồ nổi tiếng tại thụy điển', CURRENT_DATE(),  CURRENT_DATE());
INSERT into brand (name, place, description, createddate, modifieddate) VALUES  ('Casio', 'Japan', 'SX tại nhật', CURRENT_DATE(),  CURRENT_DATE());
INSERT into brand (name, place, description, createddate, modifieddate) VALUES  ('Q&Q', 'Japan', 'SX tại nhật', CURRENT_DATE(),  CURRENT_DATE());



INSERT into watch (`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 1, 'Đồng hồ 001','Nam', 900000, 50000, '/resources/images/watch/dhnam.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(),CURRENT_DATE(),CURRENT_DATE());
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 2, 'Đồng hồ 002', 'Nam',800000, 0, '/resources/images/watch/dh5.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch (`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`) VALUES (null, 2, 3, 'Đồng hồ 003', 'Nữ',750000, 50000, '/resources/images/watch/dhnu.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 004', 'Nữ',600000, 0, '/resources/images/watch/dh9.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 1, 'Đồng hồ 005','Nam', 900000, 50000, '/resources/images/watch/dh1.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 2, 'Đồng hồ 006', 'Nam',800000, 50000, '/resources/images/watch/dh2.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 3, 'Đồng hồ 007', 'Nữ',750000, 50000, '/resources/images/watch/dh6.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 008', 'Nữ',600000, 50000, '/resources/images/watch/dh7.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 1, 'Đồng hồ 009','Nam', 900000, 50000, '/resources/images/watch/dh3.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 2, 'Đồng hồ 010', 'Nam',800000, 50000, '/resources/images/watch/dh4.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 3, 'Đồng hồ 011', 'Nữ',750000, 50000, '/resources/images/watch/dh8.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 012', 'Nữ',1000000, 50000, '/resources/images/watch/dh9.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 1, 'Đồng hồ 013','Nam', 800000, 50000, '/resources/images/watch/dh5.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 014', 'Nữ',1000000, 30000, '/resources/images/watch/dh10.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );

INSERT into watch (`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 1, 'Đồng hồ 001','Nam', 900000, 50000, '/resources/images/watch/dhnam.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(),CURRENT_DATE(),CURRENT_DATE());
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 2, 'Đồng hồ 002', 'Nam',800000, 0, '/resources/images/watch/dh5.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch (`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`) VALUES (null, 2, 3, 'Đồng hồ 003', 'Nữ',750000, 50000, '/resources/images/watch/dhnu.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 004', 'Nữ',600000, 0, '/resources/images/watch/dh9.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 1, 'Đồng hồ 005','Nam', 900000, 50000, '/resources/images/watch/dh1.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 2, 'Đồng hồ 006', 'Nam',800000, 50000, '/resources/images/watch/dh2.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 3, 'Đồng hồ 007', 'Nữ',750000, 50000, '/resources/images/watch/dh6.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 008', 'Nữ',600000, 50000, '/resources/images/watch/dh7.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 1, 'Đồng hồ 009','Nam', 900000, 50000, '/resources/images/watch/dh3.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 2, 'Đồng hồ 010', 'Nam',800000, 50000, '/resources/images/watch/dh4.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 3, 'Đồng hồ 011', 'Nữ',750000, 50000, '/resources/images/watch/dh8.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 012', 'Nữ',1000000, 50000, '/resources/images/watch/dh9.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 1, 'Đồng hồ 013','Nam', 800000, 50000, '/resources/images/watch/dh5.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 014', 'Nữ',1000000, 30000, '/resources/images/watch/dh10.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );


INSERT into watch (`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 1, 'Đồng hồ 001','Nam', 900000, 50000, '/resources/images/watch/dhnam.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(),CURRENT_DATE(),CURRENT_DATE());
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 2, 'Đồng hồ 002', 'Nam',800000, 0, '/resources/images/watch/dh5.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch (`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`) VALUES (null, 1, 3, 'Đồng hồ 003', 'Nữ',750000, 50000, '/resources/images/watch/dhnu.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 004', 'Nữ',600000, 0, '/resources/images/watch/dh9.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 1, 'Đồng hồ 005','Nam', 900000, 50000, '/resources/images/watch/dh1.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 2, 'Đồng hồ 006', 'Nam',800000, 50000, '/resources/images/watch/dh2.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 3, 'Đồng hồ 007', 'Nữ',750000, 50000, '/resources/images/watch/dh6.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 008', 'Nữ',600000, 50000, '/resources/images/watch/dh7.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 1, 'Đồng hồ 009','Nam', 900000, 50000, '/resources/images/watch/dh3.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 2, 'Đồng hồ 010', 'Nam',800000, 50000, '/resources/images/watch/dh4.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 3, 'Đồng hồ 011', 'Nữ',750000, 50000, '/resources/images/watch/dh8.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 4, 'Đồng hồ 012', 'Nữ',1000000, 50000, '/resources/images/watch/dh9.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 1, 'Đồng hồ 013','Nam', 800000, 50000, '/resources/images/watch/dh5.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 4, 'Đồng hồ 014', 'Nữ',1000000, 30000, '/resources/images/watch/dh10.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );

INSERT into watch (`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 1, 'Đồng hồ 001','Nam', 900000, 50000, '/resources/images/watch/dhnam.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(),CURRENT_DATE(),CURRENT_DATE());
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 2, 'Đồng hồ 002', 'Nam',800000, 0, '/resources/images/watch/dh5.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch (`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`) VALUES (null, 1, 3, 'Đồng hồ 003', 'Nữ',750000, 50000, '/resources/images/watch/dhnu.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 004', 'Nữ',600000, 0, '/resources/images/watch/dh9.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 1, 'Đồng hồ 005','Nam', 900000, 50000, '/resources/images/watch/dh1.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 2, 'Đồng hồ 006', 'Nam',800000, 50000, '/resources/images/watch/dh2.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 3, 'Đồng hồ 007', 'Nữ',750000, 50000, '/resources/images/watch/dh6.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 2, 4, 'Đồng hồ 008', 'Nữ',600000, 50000, '/resources/images/watch/dh7.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 1, 'Đồng hồ 009','Nam', 900000, 50000, '/resources/images/watch/dh3.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 2, 'Đồng hồ 010', 'Nam',800000, 50000, '/resources/images/watch/dh4.jpg', 0, 12, 0, 100, 41,'kim loại da trâu', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 3, 'Đồng hồ 011', 'Nữ',750000, 50000, '/resources/images/watch/dh8.jpg', 0, 12, 0, 100, 41,'kim loại da', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 4, 'Đồng hồ 012', 'Nữ',1000000, 50000, '/resources/images/watch/dh9.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 1, 1, 'Đồng hồ 013','Nam', 800000, 50000, '/resources/images/watch/dh5.jpg', 0, 12, 0, 100, 41,'kim loại da bò', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );
INSERT into watch(`id`, `type_id`, `brand_id`, `name`, `gender`, `price`, `discount`, `thumbnail`, `view`, `warranty`, `buyed`, `stock`, `size`, `material`, `waterproof`, `createddate`, `modifieddate`, `createdby`, `modifiedby`)  VALUES (null, 3, 4, 'Đồng hồ 014', 'Nữ',1000000, 30000, '/resources/images/watch/dh10.jpg', 0, 12, 0, 100, 41,'kim loại da heo', 100, CURRENT_DATE(),  CURRENT_DATE(), null, null );



Insert into slide (name, link, sort) values ('slide 1', '/resources/images/slide/slide1.png', 1);
Insert into slide (name, link, sort) values ('slide 2', '/resources/images/slide/slide2.png', 2);
Insert into slide (name, link, sort) values ('slide 3', '/resources/images/slide/slide3.png', 3);